baseURL = 'http://demo-dimecres.org/'
languageCode = "en-us"
title = "gopherblog"
theme = "hugo-sustain"

[permalinks]
post = "/:year/:month/:day/:slug"

[params]
avatar = "profile.jpg"
author = "Santiago Pastor"
description = "tutorial como construir con HUGO"

[params.social]
Github        = "username"
Email         = "email@example.com"
Twitter       = "username"
LinkedIn      = "username"
Stackoverflow = "username"
Medium        = "username"
Telegram      = "username"

## Main Menu
[[menu.main]]
name = "blog"
weight = 100
identifier = "blog"
url = "/blog/"
